/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c <DATABASE_URL> -t -o <FILE_PATH>
 *
 */

export type Json = unknown;

// Table account
export interface Account {
    id: string;
    accountId: string;
    providerId: string;
    userId: string;
    accessToken: string | null;
    refreshToken: string | null;
    idToken: string | null;
    accessTokenExpiresAt: Date | null;
    refreshTokenExpiresAt: Date | null;
    scope: string | null;
    password: string | null;
    createdAt: Date;
    updatedAt: Date;
}
export interface AccountInput {
    id: string;
    accountId: string;
    providerId: string;
    userId: string;
    accessToken?: string | null;
    refreshToken?: string | null;
    idToken?: string | null;
    accessTokenExpiresAt?: Date | null;
    refreshTokenExpiresAt?: Date | null;
    scope?: string | null;
    password?: string | null;
    createdAt?: Date;
    updatedAt: Date;
}
const account = {
    tableName: "account",
    columns: [
        "id",
        "accountId",
        "providerId",
        "userId",
        "accessToken",
        "refreshToken",
        "idToken",
        "accessTokenExpiresAt",
        "refreshTokenExpiresAt",
        "scope",
        "password",
        "createdAt",
        "updatedAt",
    ],
    requiredForInsert: ["id", "accountId", "providerId", "userId", "updatedAt"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as Account,
    $input: null as unknown as AccountInput,
} as const;

// Table billing_address
export interface BillingAddress {
    id: string;
    name: string;
    street: string;
    city: string;
    postal_code: string;
    country: string;
    state: string;
    phone_number: string | null;
}
export interface BillingAddressInput {
    id?: string;
    name: string;
    street: string;
    city: string;
    postal_code: string;
    country: string;
    state: string;
    phone_number?: string | null;
}
const billing_address = {
    tableName: "billing_address",
    columns: [
        "id",
        "name",
        "street",
        "city",
        "postal_code",
        "country",
        "state",
        "phone_number",
    ],
    requiredForInsert: [
        "name",
        "street",
        "city",
        "postal_code",
        "country",
        "state",
    ],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as BillingAddress,
    $input: null as unknown as BillingAddressInput,
} as const;

// Table case_color
export interface CaseColor {
    id: string;
    name: string;
    hex: string;
    created_at: Date;
    updated_at: Date;
    active: boolean;
}
export interface CaseColorInput {
    id?: string;
    name: string;
    hex: string;
    created_at?: Date;
    updated_at?: Date;
    active?: boolean;
}
const case_color = {
    tableName: "case_color",
    columns: ["id", "name", "hex", "created_at", "updated_at", "active"],
    requiredForInsert: ["name", "hex"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as CaseColor,
    $input: null as unknown as CaseColorInput,
} as const;

// Table case_design
export interface CaseDesign {
    id: string;
    user_id: string;
    phone_model_id: string;
    case_material_id: string;
    case_color_id: string;
    case_finish_id: string;
    width: number;
    height: number;
    has_requested_to_share_publicly: boolean;
    is_shared_publicly: boolean;
    saved_by_user_ids: string[];
    total_saves: number;
    favorited_by_user_ids: string[];
    total_favorites: number;
    name: string;
    image: string | null;
    gallery_image_id: string | null;
    created_at: Date;
    updated_at: Date;
    last_reminder_sent_at: Date | null;
    unfinished: boolean;
    cropped_image_url: string | null;
}
export interface CaseDesignInput {
    id?: string;
    user_id: string;
    phone_model_id: string;
    case_material_id: string;
    case_color_id: string;
    case_finish_id: string;
    width: number;
    height: number;
    has_requested_to_share_publicly?: boolean;
    is_shared_publicly?: boolean;
    saved_by_user_ids?: string[];
    total_saves?: number;
    favorited_by_user_ids?: string[];
    total_favorites?: number;
    name: string;
    image?: string | null;
    gallery_image_id?: string | null;
    created_at?: Date;
    updated_at?: Date;
    last_reminder_sent_at?: Date | null;
    unfinished?: boolean;
    cropped_image_url?: string | null;
}
const case_design = {
    tableName: "case_design",
    columns: [
        "id",
        "user_id",
        "phone_model_id",
        "case_material_id",
        "case_color_id",
        "case_finish_id",
        "width",
        "height",
        "has_requested_to_share_publicly",
        "is_shared_publicly",
        "saved_by_user_ids",
        "total_saves",
        "favorited_by_user_ids",
        "total_favorites",
        "name",
        "image",
        "gallery_image_id",
        "created_at",
        "updated_at",
        "last_reminder_sent_at",
        "unfinished",
        "cropped_image_url",
    ],
    requiredForInsert: [
        "user_id",
        "phone_model_id",
        "case_material_id",
        "case_color_id",
        "case_finish_id",
        "width",
        "height",
        "name",
    ],
    primaryKey: "id",
    foreignKeys: {
        user_id: {
            table: "user",
            column: "id",
            $type: null as unknown as User,
        },
        phone_model_id: {
            table: "phone_model",
            column: "id",
            $type: null as unknown as PhoneModel,
        },
        case_material_id: {
            table: "case_material",
            column: "id",
            $type: null as unknown as CaseMaterial,
        },
        case_color_id: {
            table: "case_color",
            column: "id",
            $type: null as unknown as CaseColor,
        },
        case_finish_id: {
            table: "case_finish",
            column: "id",
            $type: null as unknown as CaseFinish,
        },
        gallery_image_id: {
            table: "gallery_image",
            column: "id",
            $type: null as unknown as GalleryImage,
        },
    },
    $type: null as unknown as CaseDesign,
    $input: null as unknown as CaseDesignInput,
} as const;

// Table case_finish
export interface CaseFinish {
    id: string;
    name: string;
    price: number;
    description: string | null;
    created_at: Date;
    updated_at: Date;
    active: boolean;
}
export interface CaseFinishInput {
    id?: string;
    name: string;
    price: number;
    description?: string | null;
    created_at?: Date;
    updated_at?: Date;
    active?: boolean;
}
const case_finish = {
    tableName: "case_finish",
    columns: [
        "id",
        "name",
        "price",
        "description",
        "created_at",
        "updated_at",
        "active",
    ],
    requiredForInsert: ["name", "price"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as CaseFinish,
    $input: null as unknown as CaseFinishInput,
} as const;

// Table case_material
export interface CaseMaterial {
    id: string;
    name: string;
    price: number;
    description: string | null;
    created_at: Date;
    updated_at: Date;
    active: boolean;
}
export interface CaseMaterialInput {
    id?: string;
    name: string;
    price: number;
    description?: string | null;
    created_at?: Date;
    updated_at?: Date;
    active?: boolean;
}
const case_material = {
    tableName: "case_material",
    columns: [
        "id",
        "name",
        "price",
        "description",
        "created_at",
        "updated_at",
        "active",
    ],
    requiredForInsert: ["name", "price"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as CaseMaterial,
    $input: null as unknown as CaseMaterialInput,
} as const;

// Table gallery_image
export interface GalleryImage {
    id: string;
    url: string;
    created_at: Date;
    updated_at: Date;
    active: boolean | null;
}
export interface GalleryImageInput {
    id?: string;
    url: string;
    created_at?: Date;
    updated_at?: Date;
    active?: boolean | null;
}
const gallery_image = {
    tableName: "gallery_image",
    columns: ["id", "url", "created_at", "updated_at", "active"],
    requiredForInsert: ["url"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as GalleryImage,
    $input: null as unknown as GalleryImageInput,
} as const;

// Table order
export interface Order {
    id: string;
    user_id: string;
    order_number: string;
    case_design_id: string;
    sub_total: number;
    tax: number;
    total_amount: number;
    order_status: string;
    tracking_number: string | null;
    billing_address_id: string | null;
    shipping_address_id: string | null;
    created_at: Date;
    updated_at: Date;
    is_paid: boolean | null;
}
export interface OrderInput {
    id?: string;
    user_id: string;
    order_number?: string;
    case_design_id: string;
    sub_total: number;
    tax: number;
    total_amount: number;
    order_status: string;
    tracking_number?: string | null;
    billing_address_id?: string | null;
    shipping_address_id?: string | null;
    created_at?: Date;
    updated_at?: Date;
    is_paid?: boolean | null;
}
const order = {
    tableName: "order",
    columns: [
        "id",
        "user_id",
        "order_number",
        "case_design_id",
        "sub_total",
        "tax",
        "total_amount",
        "order_status",
        "tracking_number",
        "billing_address_id",
        "shipping_address_id",
        "created_at",
        "updated_at",
        "is_paid",
    ],
    requiredForInsert: [
        "user_id",
        "case_design_id",
        "sub_total",
        "tax",
        "total_amount",
        "order_status",
    ],
    primaryKey: "id",
    foreignKeys: {
        user_id: {
            table: "user",
            column: "id",
            $type: null as unknown as User,
        },
        case_design_id: {
            table: "case_design",
            column: "id",
            $type: null as unknown as CaseDesign,
        },
        billing_address_id: {
            table: "billing_address",
            column: "id",
            $type: null as unknown as BillingAddress,
        },
        shipping_address_id: {
            table: "shipping_address",
            column: "id",
            $type: null as unknown as ShippingAddress,
        },
    },
    $type: null as unknown as Order,
    $input: null as unknown as OrderInput,
} as const;

// Table phone_model
export interface PhoneModel {
    id: string;
    model_name: string;
    model_brand: string | null;
    created_at: Date;
    updated_at: Date;
    active: boolean;
}
export interface PhoneModelInput {
    id?: string;
    model_name: string;
    model_brand?: string | null;
    created_at?: Date;
    updated_at?: Date;
    active?: boolean;
}
const phone_model = {
    tableName: "phone_model",
    columns: [
        "id",
        "model_name",
        "model_brand",
        "created_at",
        "updated_at",
        "active",
    ],
    requiredForInsert: ["model_name"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as PhoneModel,
    $input: null as unknown as PhoneModelInput,
} as const;

// Table reminders
export interface Reminders {
    id: string;
    user_id: string;
    case_design_id: string;
    status: string;
    reminder_sent_count: number;
    last_sent_at: Date | null;
    dismissed_at: Date | null;
    created_at: Date;
    updated_at: Date;
}
export interface RemindersInput {
    id?: string;
    user_id: string;
    case_design_id: string;
    status?: string;
    reminder_sent_count?: number;
    last_sent_at?: Date | null;
    dismissed_at?: Date | null;
    created_at?: Date;
    updated_at?: Date;
}
const reminders = {
    tableName: "reminders",
    columns: [
        "id",
        "user_id",
        "case_design_id",
        "status",
        "reminder_sent_count",
        "last_sent_at",
        "dismissed_at",
        "created_at",
        "updated_at",
    ],
    requiredForInsert: ["user_id", "case_design_id"],
    primaryKey: "id",
    foreignKeys: {
        user_id: {
            table: "user",
            column: "id",
            $type: null as unknown as User,
        },
        case_design_id: {
            table: "case_design",
            column: "id",
            $type: null as unknown as CaseDesign,
        },
    },
    $type: null as unknown as Reminders,
    $input: null as unknown as RemindersInput,
} as const;

// Table session
export interface Session {
    id: string;
    expiresAt: Date;
    token: string;
    createdAt: Date;
    updatedAt: Date;
    ipAddress: string | null;
    userAgent: string | null;
    userId: string;
    impersonatedBy: string | null;
}
export interface SessionInput {
    id: string;
    expiresAt: Date;
    token: string;
    createdAt?: Date;
    updatedAt: Date;
    ipAddress?: string | null;
    userAgent?: string | null;
    userId: string;
    impersonatedBy?: string | null;
}
const session = {
    tableName: "session",
    columns: [
        "id",
        "expiresAt",
        "token",
        "createdAt",
        "updatedAt",
        "ipAddress",
        "userAgent",
        "userId",
        "impersonatedBy",
    ],
    requiredForInsert: ["id", "expiresAt", "token", "updatedAt", "userId"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as Session,
    $input: null as unknown as SessionInput,
} as const;

// Table shipping_address
export interface ShippingAddress {
    id: string;
    name: string;
    street: string;
    city: string;
    postal_code: string;
    country: string;
    state: string;
    phone_number: string | null;
}
export interface ShippingAddressInput {
    id?: string;
    name: string;
    street: string;
    city: string;
    postal_code: string;
    country: string;
    state: string;
    phone_number?: string | null;
}
const shipping_address = {
    tableName: "shipping_address",
    columns: [
        "id",
        "name",
        "street",
        "city",
        "postal_code",
        "country",
        "state",
        "phone_number",
    ],
    requiredForInsert: [
        "name",
        "street",
        "city",
        "postal_code",
        "country",
        "state",
    ],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as ShippingAddress,
    $input: null as unknown as ShippingAddressInput,
} as const;

// Table user
export interface User {
    id: string;
    name: string;
    email: string;
    emailVerified: boolean;
    image: string | null;
    createdAt: Date;
    updatedAt: Date;
    username: string | null;
    displayUsername: string | null;
    role: string | null;
    banned: boolean | null;
    banReason: string | null;
    banExpires: Date | null;
}
export interface UserInput {
    id: string;
    name: string;
    email: string;
    emailVerified: boolean;
    image?: string | null;
    createdAt?: Date;
    updatedAt?: Date;
    username?: string | null;
    displayUsername?: string | null;
    role?: string | null;
    banned?: boolean | null;
    banReason?: string | null;
    banExpires?: Date | null;
}
const user = {
    tableName: "user",
    columns: [
        "id",
        "name",
        "email",
        "emailVerified",
        "image",
        "createdAt",
        "updatedAt",
        "username",
        "displayUsername",
        "role",
        "banned",
        "banReason",
        "banExpires",
    ],
    requiredForInsert: ["id", "name", "email", "emailVerified"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as User,
    $input: null as unknown as UserInput,
} as const;

// Table verification
export interface Verification {
    id: string;
    identifier: string;
    value: string;
    expiresAt: Date;
    createdAt: Date;
    updatedAt: Date;
}
export interface VerificationInput {
    id: string;
    identifier: string;
    value: string;
    expiresAt: Date;
    createdAt?: Date;
    updatedAt?: Date;
}
const verification = {
    tableName: "verification",
    columns: [
        "id",
        "identifier",
        "value",
        "expiresAt",
        "createdAt",
        "updatedAt",
    ],
    requiredForInsert: ["id", "identifier", "value", "expiresAt"],
    primaryKey: "id",
    foreignKeys: {},
    $type: null as unknown as Verification,
    $input: null as unknown as VerificationInput,
} as const;

export interface TableTypes {
    account: {
        select: Account;
        input: AccountInput;
    };
    billing_address: {
        select: BillingAddress;
        input: BillingAddressInput;
    };
    case_color: {
        select: CaseColor;
        input: CaseColorInput;
    };
    case_design: {
        select: CaseDesign;
        input: CaseDesignInput;
    };
    case_finish: {
        select: CaseFinish;
        input: CaseFinishInput;
    };
    case_material: {
        select: CaseMaterial;
        input: CaseMaterialInput;
    };
    gallery_image: {
        select: GalleryImage;
        input: GalleryImageInput;
    };
    order: {
        select: Order;
        input: OrderInput;
    };
    phone_model: {
        select: PhoneModel;
        input: PhoneModelInput;
    };
    reminders: {
        select: Reminders;
        input: RemindersInput;
    };
    session: {
        select: Session;
        input: SessionInput;
    };
    shipping_address: {
        select: ShippingAddress;
        input: ShippingAddressInput;
    };
    user: {
        select: User;
        input: UserInput;
    };
    verification: {
        select: Verification;
        input: VerificationInput;
    };
}

export const tables = {
    account,
    billing_address,
    case_color,
    case_design,
    case_finish,
    case_material,
    gallery_image,
    order,
    phone_model,
    reminders,
    session,
    shipping_address,
    user,
    verification,
};
